// This helper automatically translates any text
// If translation exists, use it; if not, keep original
export function autoTranslate(text, locale) {
  if (locale === 'en') return text
  
  // Common word mappings
  const translations = {
    'en': {
      'Dashboard': 'Dashboard',
      'Invoices': 'Invoices',
      'Clients': 'Clients',
      'Expenses': 'Expenses',
      'Save': 'Save',
      'Cancel': 'Cancel',
      'Delete': 'Delete',
      'Edit': 'Edit',
      'View': 'View',
      'Add': 'Add',
      'Create': 'Create',
      'Update': 'Update',
      'Back': 'Back',
      'Search': 'Search',
      'Export': 'Export',
      'Name': 'Name',
      'Email': 'Email',
      'Phone': 'Phone',
      'Amount': 'Amount',
      'Date': 'Date',
      'Status': 'Status',
      'Total': 'Total',
      'Subtotal': 'Subtotal',
      'Tax': 'Tax',
      'Discount': 'Discount',
    },
    'es': {
      'Dashboard': 'Tablero',
      'Invoices': 'Facturas',
      'Clients': 'Clientes',
      'Expenses': 'Gastos',
      'Save': 'Guardar',
      'Cancel': 'Cancelar',
      'Delete': 'Eliminar',
      'Edit': 'Editar',
      'View': 'Ver',
      'Add': 'Agregar',
      'Create': 'Crear',
      'Update': 'Actualizar',
      'Back': 'Atrás',
      'Search': 'Buscar',
      'Export': 'Exportar',
      'Name': 'Nombre',
      'Email': 'Correo',
      'Phone': 'Teléfono',
      'Amount': 'Monto',
      'Date': 'Fecha',
      'Status': 'Estado',
      'Total': 'Total',
      'Subtotal': 'Subtotal',
      'Tax': 'Impuesto',
      'Discount': 'Descuento',
    },
    'fr': {
      'Dashboard': 'Tableau de bord',
      'Invoices': 'Factures',
      'Clients': 'Clients',
      'Expenses': 'Dépenses',
      'Save': 'Enregistrer',
      'Cancel': 'Annuler',
      'Delete': 'Supprimer',
      'Edit': 'Modifier',
      'View': 'Voir',
      'Add': 'Ajouter',
      'Create': 'Créer',
      'Update': 'Mettre à jour',
      'Back': 'Retour',
      'Search': 'Rechercher',
      'Export': 'Exporter',
      'Name': 'Nom',
      'Email': 'E-mail',
      'Phone': 'Téléphone',
      'Amount': 'Montant',
      'Date': 'Date',
      'Status': 'Statut',
      'Total': 'Total',
      'Subtotal': 'Sous-total',
      'Tax': 'Taxe',
      'Discount': 'Réduction',
    },
    'ar': {
      'Dashboard': 'لوحة التحكم',
      'Invoices': 'الفواتير',
      'Clients': 'العملاء',
      'Expenses': 'المصروفات',
      'Save': 'حفظ',
      'Cancel': 'إلغاء',
      'Delete': 'حذف',
      'Edit': 'تعديل',
      'View': 'عرض',
      'Add': 'إضافة',
      'Create': 'إنشاء',
      'Update': 'تحديث',
      'Back': 'رجوع',
      'Search': 'بحث',
      'Export': 'تصدير',
      'Name': 'الاسم',
      'Email': 'البريد',
      'Phone': 'الهاتف',
      'Amount': 'المبلغ',
      'Date': 'التاريخ',
      'Status': 'الحالة',
      'Total': 'المجموع',
      'Subtotal': 'المجموع الفرعي',
      'Tax': 'الضريبة',
      'Discount': 'الخصم',
    },
  }
  
  return translations[locale]?.[text] || text
}
